services:
  model1:
    image: solomonrocks/crypto_sentiment_model:latest
    container_name: crypto_sentiment_model_1
    ports:
      - "3001:5001"
    environment:
      - MLFLOW_TRACKING_URI=NGROK_URL_PLACEHOLDER
      - MODEL_NAME=crypto_sentiment_model_1

  model2:
    image: solomonrocks/crypto_sentiment_model:latest
    container_name: AAPL
    ports:
      - "3002:5001"
    environment:
      - MLFLOW_TRACKING_URI=NGROK_URL_PLACEHOLDER
      - MODEL_NAME=AAPL

  model3:
    image: solomonrocks/crypto_sentiment_model:latest
    container_name: AMD
    ports:
      - "3003:5001"
    environment:
      - MLFLOW_TRACKING_URI=NGROK_URL_PLACEHOLDER
      - MODEL_NAME=AMD

  model4:
    image: solomonrocks/crypto_sentiment_model:latest
    container_name: AMZN
    ports:
      - "3004:5001"
    environment:
      - MLFLOW_TRACKING_URI=NGROK_URL_PLACEHOLDER
      - MODEL_NAME=AMZN

  model5:
    image: solomonrocks/crypto_sentiment_model:latest
    container_name: BA
    ports:
      - "3005:5001"
    environment:
      - MLFLOW_TRACKING_URI=NGROK_URL_PLACEHOLDER
      - MODEL_NAME=BA

  model6:
    image: solomonrocks/crypto_sentiment_model:latest
    container_name: DIS
    ports:
      - "3006:5001"
    environment:
      - MLFLOW_TRACKING_URI=NGROK_URL_PLACEHOLDER
      - MODEL_NAME=DIS

  model7:
    image: solomonrocks/crypto_sentiment_model:latest
    container_name: GOOGL
    ports:
      - "3007:5001"
    environment:
      - MLFLOW_TRACKING_URI=NGROK_URL_PLACEHOLDER
      - MODEL_NAME=GOOGL

  model8:
    image: solomonrocks/crypto_sentiment_model:latest
    container_name: INTC
    ports:
      - "3008:5001"
    environment:
      - MLFLOW_TRACKING_URI=NGROK_URL_PLACEHOLDER
      - MODEL_NAME=INTC

  model9:
    image: solomonrocks/crypto_sentiment_model:latest
    container_name: JPM
    ports:
      - "3009:5001"
    environment:
      - MLFLOW_TRACKING_URI=NGROK_URL_PLACEHOLDER
      - MODEL_NAME=JPM

  model10:
    image: solomonrocks/crypto_sentiment_model:latest
    container_name: META
    ports:
      - "3010:5001"
    environment:
      - MLFLOW_TRACKING_URI=NGROK_URL_PLACEHOLDER
      - MODEL_NAME=META

  model11:
    image: solomonrocks/crypto_sentiment_model:latest
    container_name: MSFT
    ports:
      - "3011:5001"
    environment:
      - MLFLOW_TRACKING_URI=NGROK_URL_PLACEHOLDER
      - MODEL_NAME=MSFT

  model12:
    image: solomonrocks/crypto_sentiment_model:latest
    container_name: NFLX
    ports:
      - "3012:5001"
    environment:
      - MLFLOW_TRACKING_URI=NGROK_URL_PLACEHOLDER
      - MODEL_NAME=NFLX

  model13:
    image: solomonrocks/crypto_sentiment_model:latest
    container_name: NKE
    ports:
      - "3013:5001"
    environment:
      - MLFLOW_TRACKING_URI=NGROK_URL_PLACEHOLDER
      - MODEL_NAME=NKE

  model14:
    image: solomonrocks/crypto_sentiment_model:latest
    container_name: NVDA
    ports:
      - "3014:5001"
    environment:
      - MLFLOW_TRACKING_URI=NGROK_URL_PLACEHOLDER
      - MODEL_NAME=NVDA

  model15:
    image: solomonrocks/crypto_sentiment_model:latest
    container_name: TSLA
    ports:
      - "3015:5001"
    environment:
      - MLFLOW_TRACKING_URI=NGROK_URL_PLACEHOLDER
      - MODEL_NAME=TSLA

  model16:
    image: solomonrocks/crypto_sentiment_model:latest
    container_name: V_MODEL
    ports:
      - "3016:5001"
    environment:
      - MLFLOW_TRACKING_URI=NGROK_URL_PLACEHOLDER
      - MODEL_NAME=V
