name: Daily Crypto Pipeline

on:
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch:

jobs:
  run-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.0'

      - name: Install dependencies
        run: pip install -r requirements.txt
        
      - name: Install NLTK
        run: |
          pip install nltk
          python -c "import nltk, os; path=os.path.join(os.getcwd(), 'nltk_data'); nltk.download('punkt', download_dir=path); nltk.download('stopwords', download_dir=path); nltk.download('wordnet', download_dir=path)"

      - name: Set NLTK_DATA environment variable
        run: echo "NLTK_DATA=/usr/local/share/nltk_data" >> $GITHUB_ENV

      - name: Start MLflow model server on port 5003
        run: |
          nohup mlflow server --host 0.0.0.0 --port 5003 &> mlflow.log &
      
      - name: Deploy Model on port 5002
        run: |
          python deploy_model.py

      - name: Install ngrok
        run: |
          curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null
          echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | sudo tee /etc/apt/sources.list.d/ngrok.list
          sudo apt update && sudo apt install ngrok

      - name: Create ngrok config file
        run: |
          mkdir -p ~/.ngrok2
          cat <<EOF > ~/.ngrok2/ngrok.yml
          authtoken: ${{ secrets.NGROK_AUTHTOKEN }}
          version: "2"
          tunnels:
            model_api:
              addr: 5002
              proto: http
            mlflow_ui:
              addr: 5003
              proto: http
          web_addr: 127.0.0.1:4040
          EOF

      - name: Authenticate ngrok
        run: ngrok config add-authtoken ${{ secrets.NGROK_AUTHTOKEN }}
      
      - name: Start ngrok with multiple tunnels
        run: |
          nohup ngrok start --all > ngrok.log &

      - name: Get public URLs from ngrok
        run: |
          echo "Waiting for ngrok to initialize..."
          for i in {1..10}; do
            RESPONSE=$(curl -s http://127.0.0.1:4040/api/tunnels)
            MODEL_URL=$(echo "$RESPONSE" | jq -r '.tunnels[] | select(.name=="model_api") | .public_url')
            MLFLOW_URL=$(echo "$RESPONSE" | jq -r '.tunnels[] | select(.name=="mlflow_ui") | .public_url')

            if [[ -n "$MODEL_URL" && "$MODEL_URL" != "null" && -n "$MLFLOW_URL" && "$MLFLOW_URL" != "null" ]]; then
              echo "Model URL: $MODEL_URL"
              echo "MLflow URL: $MLFLOW_URL"
              echo "API_SENTIMENT_MODEL=$MODEL_URL/invocations" >> $GITHUB_ENV
              echo "MLFLOW_NGROK=$MLFLOW_URL" >> $GITHUB_ENV
              break
            fi
            sleep 3
          done

          # Debugging: Print the URLs
          echo "Final Model URL: $MODEL_URL"
          echo "Final MLflow URL: $MLFLOW_URL"

      - name: Set API URL environment variable
        run: |
          echo "API_SENTIMENT_MODEL=${{ env.PUBLIC_URL }}/invocations" >> $GITHUB_ENV
          echo "MLFLOW_NGROK=${{ env.MLFLOW_URL }}" >> $GITHUB_ENV

      # -------------------------------------------------------------------------------------------

      # - name: Run get_news_sentences.py
      #   run: python get_news_sentences.py
      #   env:
      #     API_SENTIMENT_MODEL: ${{ env.API_SENTIMENT_MODEL }}

      # - name: Preprocess sentiments
      #   run: python clean_headline_sentiment.py

      # - name: Combine final dataset
      #   run: python generate_csv.py

      - name: Predict tomorrow's price
        run: python price_model.py
        env:
          MLFLOW_NGROK: ${{ env.MLFLOW_NGROK }}
      
      - name: Upload prediction result
        uses: actions/upload-artifact@v4
        with:
          name: prediction_result
          path: prediction_result.txt

# 2vjKe8gcVkpxr6d6NW2uVeQm5VJ_4yWBF6Qu2MMLi2UarA4wT : 5002
# 2wFydqD901sz9dzcxcfpfxocQvD_58Ex39kxnNgMR7gWiV8jL : 5001